apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
  affinity:
    nodeAffinity:
      # requiredDuringSchedulingIgnoreDuringExecution:
      #   nodeSelectorTerms:
      #   - matchExpression:
      #     - key: "hardware"
      #       operator: In 
      #       values: 
      #       - gpu
      preferredDuringSchedulingIgnoreDuringExecution:
      - weight: 4
        preference:
        - matchExpressions:
          - key: "hardware"
            operator: In
            values:
            - gpu
  containers:
   - name: nginx
     image: nginx