apiVersion: v1
kind: Pod
metadata:
  name: nod-anti-affinity
spec:
  affinity:
    nodeaffinity:
      required  DuringSchedulingIgnoreDuringExecution:
       nodeSelectorTerms:
        - matchExpressions:
          - key: "hardware"
            operator: NotIn
            values:
            - gpu
  containers:
   - name: nginx
     image: nginx