apiVersion: v1
kind: Pod
metadata:
  name: toleration
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    disktype: ssd
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoExecute"
  - key: "key2"
    operator: "Equal"
    value: "value2"
    effect: "NoSchedule"